name: velocity_log_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: 2.6.1
  geolocator: ^14.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_background_service: ^5.1.0
  syncfusion_flutter_gauges: ^31.1.19
  uuid: ^4.5.3
  intl: ^0.20.2
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_map_location_marker: ^10.2.0
  flutter_secure_storage: ^10.0.0
  share_plus: ^12.0.2
  path_provider: ^2.1.5
  logger: ^2.7.0
  wakelock_plus: ^1.5.2
  flutter_local_notifications: ^21.0.0
  vibration: ^3.1.8
  geolocator_android: ^5.0.2
  geolocator_apple: ^2.3.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
